apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arch-api-idempotence.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%s/orders" (include "arch-api-idempotence.db.fullname" .) .Values.postgresql.service.port }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.postgresqlUsername }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arch-api-idempotence.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
